### ISSUE TITLE
[REQ] Add event for pages extension into top_bar.html

### ISSUE THREAD

**Issue by jakubsuchygit** [PayBas/style-PBTech#8]
Hello,
on my forum I wanted to make static button links to pages from pages extension in pbtech top bar, so I added.
            
After the first li of linklist in top_bar.html

Hope you like it, because I do. :) reference: http://forum-new.soe.cz/index.php
Thanks. Biosek.

**Comment by PayBas** [comment]
It's not that simple. You'd have to modify the pages ext as well, or else it will have no idea that the extra template location is available.

**Comment by jakubsuchygit** [comment]
Yes that is what I have done and when pbtech has this event i will also notify pages developers to kindly add it :)

**Comment by PayBas** [comment]
I'll add `<!-- EVENT top_bar_links_before -->` and `<!-- EVENT top_bar_links_after -->`, but I doubt the team will add them, since these events are not supported by most styles.

**Comment by jakubsuchygit** [comment]
I think that extension pages have those links added by style templates, so they could add templates for your specific style. We will see.
But hey, more events = more possibilities for third party extensions, so I think this is overall a good thing.
Thank you very much.

**Comment by PayBas** [comment]
Done
